# Generated by Django 3.0.7 on 2020-06-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_song_is_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_logo',
        ),
    ]
